import flet as ft

# ==== PAGE SETTINGS ====
PAGE_TITLE = "A.V.R.O.R.A"
PAGE_THEME = ft.ThemeMode.DARK

# ==== LOGGING ====
LOGGING_FILENAME = "avrora.log"

# ==== WINDOW SETTINGS ====
WINDOW_WIDTH = 450
WINDOW_HEIGHT = 665
WINDOW_MIN_WIDTH = 450
WINDOW_MAX_WIDTH = 450
WINDOW_MAX_HEIGHT = 665
WINDOW_MIN_HEIGHT = 665

# ==== RECORDING ====
AUDIO_FILENAME = "record.wav"
AUDIO_FILES_FOLDER = "./audio/"
FREQUENCY = 44100
DURATION = 5